language: node_js

node_js:
  - '10'

# Install Chrome addon
addons:
  - chrome: stable

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sleep 1 # give server time to start

script:
  - npm run test-single-run